Adding ButterCMS Starter
gridsome/gridsome.org pull request #344
Opened 2020-01-29 20:59 UTC by jakelumetta

We're big fans of Gridsome and Vue so we're excited to launch this Starter project that utilizes our new Plugin (https://gridsome.org/plugins/gridsome-source-buttercms) for CMS-powered marketing page + blog app.

Looking forward to any feedback / questions.

We'll be launching a better guide for our plugin very soon as well.

2020-02-04 21:09 UTC, jakelumetta commented
Hi @tomtev - who's the best person to tag for reviewing this type of PR?  Thanks much!

2020-02-14 06:50 UTC, tomtev commented
Hi :) 

These does not seem to work:
repo: ButterCMS/gridsome-starter-buttercms
preview: https://buttercms-gridsome-starter.netlify.com/

That repo on Github also has node_modules and does not look like a Gridsome project.

2020-02-14 20:02 UTC, jakelumetta commented
Hey @tomtev - Sorry about that.  We've corrected both the repo and the starter project:  https://buttercms-gridsome-starter.netlify.com/

2020-02-24 20:27 UTC, jakelumetta commented
Hi - @tomtev 

Is this looking good to you now? Thanks!

2020-03-01 15:01 UTC, jakelumetta commented
Hi @hjvedvik - any chance you could take a look at this?  We're (ButterCMS) looking really ramp up our support of Gridsome.

2020-03-24 20:29 UTC, tomtev commented
Still not linking to correct starter 😅 Need to be a complete Github url to the starter

2020-03-24 21:25 UTC, jakelumetta commented
Are you referring to these URLs?  https://share.getcloudapp.com/2NuB8pBn

2020-05-14 17:18 UTC, jakelumetta commented
Hi @tomtev - just following up. Would love to get this merged in.

2020-07-11 23:55 UTC, mtlynch requested changes
Thanks for submitting, @jakelumetta!

I checked out the repo and it still seems to be incomplete as a starter. I filed some bugs on the things that prevent it from being complete:

https://github.com/ButterCMS/gridsome-starter-buttercms/issues/created_by/mtlynch

~~If you address those issues, I can merge this in.~~

### Update (2020-09-09)

I am no longer willing to review this PR.

I don't feel that the Gridsome team is practicing due diligence in what they submit for review. Simple bugs I've filed have required months of back-and-forths. I went into more detail on [this issue comment](https://github.com/ButterCMS/gridsome-starter-buttercms/issues/9).

I do not speak on behalf of the Gridsome team, so someone else might be willing to review this and help you get it merged in.

2020-07-11 23:55 UTC, mtlynch commented on src/components/home/HomeHowItWorkSimple.vue
> +        <p>Any Headless CMS, <a href="https://buttercms.com">ButterCMS</a>, Contentful, WordPress, Drupal, Sanity.io, etc.</p>
Can we remove the link here? There are lots of companies mentioned on this page, so we should either be linking all of them or none of them.

2020-07-11 23:55 UTC, mtlynch commented on src/components/home/HomeHowItWorks.vue
> +          <p>Any Headless CMS, <a href="https://buttercms.com">ButterCMS</a>, Contentful, WordPress, Drupal, DatoCMS, Sanity.io, GraphCMS etc.</p>
Ditto about linking here.

2020-09-21 17:05 UTC, jonalecpalustre commented
We've taken care of the other issues for our Gridsome starter here - https://github.com/ButterCMS/gridsome-starter-buttercms/issues?q=is%3Aissue+author%3Amtlynch+is%3Aclosed

Also, remove links that was requested by Michael above.

2020-09-21 17:06 UTC, jonalecpalustre commented
@tomtev Would you be able to assist on reviewing and merging this PR please? Thank you!

2021-01-25 18:46 UTC, jakelumetta commented
@tomtev  @mtlynch Happy New Year.  Any chance we can get a final review here?

2021-02-12 16:05 UTC, closed without merging